### ISSUE TITLE
Console errors when using the CharMaker

### ISSUE THREAD

**Issue by Nyxaion** [coco875/CharMaker#1]
Hello.
As per the title, I get a bunch of errors on the console when I try to use the CharMaker. Here they are:
[errors](https://media.discordapp.net/attachments/837849080457199646/952891093928783923/Console_CharaMaker_errors.png?width=750&height=664). Do you know what causes the errors? How do I solve this?
Thanks for reading.

**Comment by coco875** [comment]
this plugin is in developpment is fixed in the next pull and now I make the compatibility with web so if you use web it's doesn't work now is fix in the future.

**Comment by Nyxaion** [comment]
Thanks for your quick reply! It solved the existing issue, but the plugin doesn't work yet. Here is [the new error](https://media.discordapp.net/attachments/837849080457199646/952936483399028756/New_error_CharMaker.png?width=736&height=664).
