### ISSUE TITLE
Character disappearing

### ISSUE THREAD

**Issue by OneEyedTiamat** [coco875/CharMaker#5]
Hey.
I'm having an issue with the saved character. When I use the menu by using Esc or after a battle, the character disappears and I can't seem to make it come back. I can provide a sample game with the issue if you need me to.

**Comment by OneEyedTiamat** [comment]
The sprite that allows the player to move on the map disappears.

**Comment by coco875** [comment]
ok but how reproduce it and do you have the last version I made (I actualise very actively because I fix bug and make a ui better)

**Comment by coco875** [comment]
very strang for me he doesn't do this with menu, I don't try for now with battle because I am pretty sure then make bug but is more important to fix for menu. ok i want the project to see reproduce and debug this

**Comment by OneEyedTiamat** [comment]
I just got back to my computer. [Here is the file.](https://drive.google.com/file/d/1ic000eS1q4_XyQPCtqklJD_R1b3KrrE7/view?usp=sharing)

**Comment by coco875** [comment]
ok reproduce it I think it can be caused be other plugin so I analyse this to see

**Comment by coco875** [comment]
oh it's crypted ... let's go see in superficy what function in game he use
![image](https://user-images.githubusercontent.com/59367621/158468886-40cad613-556c-4d5f-a46f-dbbd30252a2f.png)

**Comment by coco875** [comment]
I fix this later because is a to heavy for me I think it's take long time to patch because the plugin is obfuscated.

**Comment by coco875** [comment]
ok I fix this is pretty easy and I fix a other bug in the same time
